<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit49d94e40636e8e04f987ea53a3f40439
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit49d94e40636e8e04f987ea53a3f40439::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit49d94e40636e8e04f987ea53a3f40439::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
